---
- ansible.builtin.import_tasks: 05-read-state.yml
  when: terraform_states is defined
  delegate_to: localhost
  run_once: true
  become: false
  connection: local
  # tags: ['always', 'tf', 'state']
  tags:
    - tf
    - ufw
    - tf-data
    - state
    - k8s
    - k8s-addition
    - k8s-label
    - k8s-ingress-nginx
