---
- name: create docker folder
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: '0775'
    owner: root
    group: root
  with_items:
    - "/opt/docker"
    - "{{ dkron_compose_path }}"

- name: create dkron folders
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
    owner: root
    group: root
  with_items:
    - "{{ dkron_data_path }}"
    - "{{ dkron_config_path }}"

- name: create dkron folder - unit
  ansible.builtin.file:
    path: "/etc/dkron"
    state: directory
    mode: '0755'
    owner: root
    group: root
  when: dkron_server_compose is not defined
