---
teleport_registry: public.ecr.aws/gravitational/teleport-distroless
teleport_version: 18.3.1

teleport_compose_path: "/opt/docker/teleport"
teleport_data_path: /opt/teleport

teleport_cluster_name: cls1
teleport_public_addr: "teleport.example.com:443"

teleport_acme_email: user@example.com
teleport_node_name: "{{ inventory_hostname_short }}"
