---
- name: apply labels to nodes - chnages always
  ansible.builtin.command: >
    kubectl label nodes {{ item.hostname }}
    {% for label_key, label_value in item.labels.items() %}
    {{ label_key }}={{ label_value }}
    {% endfor %}
    --overwrite
    --kubeconfig {{ k8s_config_path }}
  loop: "{{ k8s_hands_nodes_with_labels }}"
  # changed_when: false
