---
- name: VSO - Ensure Helm is installed
  ansible.builtin.command: helm version
  register: helm_check
  failed_when: helm_check.rc != 0
  changed_when: false

- name: VSO - Check if vault-secrets-operator is already installed
  ansible.builtin.shell: |
    helm list -n {{ helm_vso_namespace | default('vault-secrets-operator') }} --kubeconfig {{ k8s_config_path }} | grep -w vault-secrets-operator
  register: vso_installed
  failed_when: false
  changed_when: false

- name: VSO - Set fact whether to skip install
  ansible.builtin.set_fact:
    skip_vso_install: "{{ vso_installed.rc == 0 and (not vso_force_install | default(false)) }}"

- name: VSO - Add Helm repository
  ansible.builtin.command: helm repo add hashicorp https://helm.releases.hashicorp.com
  register: helm_vso_repo
  changed_when: "'\"has been added\"' in helm_vso_repo.stdout"
  when: not skip_vso_install

- name: VSO - Update Helm repos
  ansible.builtin.command: helm repo update
  when: not skip_vso_install

- name: VSO - Create values config from template
  ansible.builtin.template:
    src: "vso-values.yaml.j2"
    dest: /tmp/vso-values.yaml
    mode: "0600"
  when: not skip_vso_install or vso_force_install is defined
  tags:
    - vso-value

- name: VSO - Install via Helm
  ansible.builtin.command: >
    helm upgrade --install vault-secrets-operator hashicorp/vault-secrets-operator
    --namespace {{ helm_vso_namespace | default('vault-secrets-operator') }}
    --version {{ helm_vso_version }}
    --kubeconfig {{ k8s_config_path }}
    --create-namespace
    --values /tmp/vso-values.yaml
  when: not skip_vso_install or vso_force_install is defined

- name: VSO - remove /tmp/vso-values.yaml
  ansible.builtin.file:
    path: /tmp/vso-values.yaml
    state: absent
