---
- name: copy ansible-management.conf
  ansible.builtin.template:
    src: gai.conf.j2
    dest: "/etc/gai.conf"
    mode: "0644"

- name: restart systemd-resolved
  ansible.builtin.systemd:
    state: restarted
    name: systemd-resolved
