concurrent = {{ runner_concurrent | default(16) }}
check_interval = 0

[session_server]
  session_timeout = 1800

[[runners]]
  name = "runner-nocache-{{ inventory_hostname_short }}"
  request_concurrency = {{ runner_concurrent | default(16) }}
  url = "{{ runner_gitlab_url | default('https://gitlab.example.com')}}"
  output_limit = 40960
  executor = "docker"
  [runners.custom_build_dir]
  [runners.docker]
    shm_size = 1073741824
#    cpuset_cpus = "0-31"
    tls_verify = false
    image = "{{ runer_docker_default_image }}"
    privileged = false
    disable_entrypoint_overwrite = false
    oom_kill_disable = false
    disable_cache = true
    volumes = ["/var/run/docker.sock:/var/run/docker.sock"]
  [runners.cache]
    MaxUploadedArchiveSize = 0