
concurrent = 16
check_interval = 0

[session_server]
  session_timeout = 1800

[[runners]]
  name = "runner-cache-{{ inventory_hostname_short }}"
  url = "https://gitlab.example.com"
  output_limit = 40960
  executor = "docker"
  [runners.custom_build_dir]
  [runners.cache]
    Path = "/cache"
    Shared = true
    MaxUploadedArchiveSize = 0
  [runners.docker]
    tls_verify = false
    image = "{{ runer_docker_default_image }}"
    privileged = false
    disable_cache = false
    volumes = ["/var/run/docker.sock:/var/run/docker.sock"]